### PR TITLE
AS/2 incoming: Pull XML document out of BusinessDocument header?

### PR DESCRIPTION
**Pull request by tjeb**
When receiving messages via the START protocol, Oxalis saves the resulting XML (in my case an <Invoice> document) into the appropriate directory. Likewise, it saves an xml document when receiving a message via AS/2. However, in the case of AS/2 this XML document still contains the BusinessMessageEnvelope structure.

Obivously this structure is needed when sending, and Oxalis wraps the actual document in it, as specified by the PEPPOL Transport Infrastructure AS2 Profile.

However, should it not automatically strip it as well, before saving, if there is an incoming AS/2 message?

I am debugging an application here that reads the document as it is stored, and hence fails (since there is new XML around the actual document), and I am trying to determine whether the application is doing the wrong thing, or Oxalis is.

This (probably very bad) branch shows the concept, and makes the application I am using work with AS/2, assuming is it Oxalis that should unwrap the envelope of course.

### CODE REVIEW

**Comment by klakegg** [comment]
As SBDH is quite important to keep, functionality to rip content out of SBDH and throw away the header is not welcome in Oxalis. If this is functionality you for any reason want, please implement it in your own MessageRepository.

**Comment by tjeb** [comment]
I understand the need to keep the SBDH information (and the rejection of this pull request), but I do have some additional questions, if you would indulge me;
- it is not a problem that right now the resulting document type differs depending on the transport protocol that is used? It seems like a layer violation :)
- could this data be pulled into the PeppolMessageMetaData? I (apparently incorrectly) assumed this was already the case.

**Comment by steinarcook** [comment]
Sorry for the late reply, I have been travelling.

The basic idea is that the SBDH should be created in C1. 

However; in order to be helpfull, we have implemented document «sniffing» in order to wrap the document within an SBD.

The long and short of this is, the AS2 message MUST always be wrapped in an SBD/SBDH.

Extracting the payload from within the SBD/SBDH is not part of the services provided by AS2.

I admit this is kind of confusing as Oxalis provides some additional functionality over what is considered a standard part of AS2.

Having said that, I guess what we need to do is to define the minimum interfaces and services to be provided by the access point as such.

**Comment by pr0nin** [comment]
I know the issue is closed but I have one question.

How many of the ERP systems used in the Norwegian market supports EHF wrapped in SBDH as a standard?

We extract the EHF payload for our customers, but that might not be necessary any more.

**Comment by steinarcook** [comment]
Unfortunately you are absolutelely right :-)

That is why I think we need to do work on the specifications of the access points. This is not a question about AS2 or any other protocol, the question is: what kind of services should be provided by the access point?

I.e. should the access point provide XML «sniffing» and SBD/SBDH wrapping? What about ASiC archive management? Should this be handled by the access point or should we impose this functionality into the ERP systems?

**Comment by pr0nin** [comment]
Absolutely. 

In my opinion all transport and routing related data should be known and logged by Oxalis (especially important for inbound). 

If some of that data is in the SBDH and not anywhere else. Oxalis should extract and handle it. It would then be up to the Access point and receiver if the SBDH has any additional value.

**Pull request closed without merging**
